apiVersion: apps/v1
kind: Deployment
metadata:
  name: crapi-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crapi-workshop
  template:
    metadata:
      labels:
        app: crapi-workshop
    spec:
      initContainers:
        - name: wait-for-crapi-identity
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
    
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
    
          securityContext:
            runAsUser: 10000         # <- Here is your update
            runAsGroup: 3000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          args:
            - "service"
            - "crapi-identity"
        - name: wait-for-crapi-community
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
    
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          securityContext:
            runAsUser: 10000         # <- Here is your update
            runAsGroup: 3000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        readOnlyRootFilesystem: true
          args:
            - "service"
            - "crapi-community"
      containers:
      - name: crapi-workshop
        image: crapi/crapi-workshop:v1
        imagePullPolicy: Always  
        ports:
        - containerPort: 8000
        envFrom:
            - configMapRef:
                name: crapi-workshop-configmap
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
  
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

        securityContext:
          runAsUser: 10000         # <- Here is your update
          runAsGroup: 3000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "256m"
            requests:
              cpu: 256m
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
