apiVersion: v1
kind: Service
metadata:
  name: crapi-web
  labels:
    app: crapi-web
spec:
  loadBalancerSourceRanges: "196.12.3.0/24"
  ports:
  - port: 80
    nodePort: 30080
    name: nginx
  type: LoadBalancer
  selector:
    app: crapi-web
