apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: crapi
  name: waitfor-grant
subjects:
- kind: ServiceAccount
  name: serviceaccount
  namespace: crapi
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: waitfor-reader
  apiGroup: ""
